### ISSUE TITLE
ISSUE: 

### ISSUE THREAD

**Issue by forensium** [FutureTense/lock-manager#88]
**Describe the bug**

No errors impacting operations identified.

**Environment (please complete the following information):**

- OS: HAOS
- Type of device: Beelink S12 and Kwikset HC620 Z-Wave
- Home Assistant version:  Operating System 12.3
   - Supervisor 2024.05.1
   - Core 2024.5.3
   - Frontend 20240501.1
- Component version: v0.0.92

**Logs**
```
   Logger: homeassistant.helpers.event
Source: helpers/event.py:327
First occurred: May 15, 2024 at 13:45:25 (8 occurrences)
Last logged: 08:27:48
Error while dispatching event for lock.mdfrontdoorlock to <Job track state_changed event ['lock.mdfrontdoorlock'] HassJobType.Callback functools.partial(<function handle_state_change at 0x7f7e5f764e00>, <HomeAssistant RUNNING>, <ConfigEntry entry_id=66eb541c91b4cccce3b7948537f276fa version=2 domain=keymaster title=MDFrontDoor state=ConfigEntryState.LOADED unique_id=mdfrontdoor>)>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 327, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 947, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/keymaster/helpers.py", line 272, in handle_state_change
    new_state = event.data["new_state"]
                ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
```
**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
This isn't the correct repo for Keymaster.
